### ISSUE TITLE
Incompatible pixel format 'yuvj420p' for codec 'libx265

### ISSUE THREAD

**Issue by bartusp-zz** [bennetimo/shrinkwrap#2]
I am unable to set pix_fmt=yuvj420p option (default pixel format for GoPro session )
The following message is displayed: 
Incompatible pixel format 'yuvj420p' for codec 'libx265', auto-selecting format 'yuv420p'
I've tried it with newest ffmpeg version and it worked fine.

Is it possible to upgrade ffmpeg version ?

**Comment by bennetimo** [comment]
Hi @bartusp, do you know which is the minimum version of ffmpeg that you need?

**Comment by AmraniRiyad** [comment]
Hi @bennetimo, first thank you for this tool, it is really helpful!
I am trying to encode to 265, and using something like : 

docker run -v path/to/files:/files bennetimo/shrinkwrap -i mp4 -c:v libx265 -c:a copy -x265-params crf=25 /files/GOPR0212.mp4 

I get 
`Error: Unknown option -c:v
Error: Unknown option -c:a
Error: Unknown option -x265-params`

So i think it might be a ffmpeg issue. So could you give a clue on how to change / update ffmpeg on your tool ?

Thank you.

**Comment by bennetimo** [comment]
Hi @AmraniRiyad, shrinkwrap builds off a minimalist [docker image](https://hub.docker.com/r/jrottenberg/ffmpeg/) of ffmpeg which should already be configured with `--enable-libx265`.

It looks like you're trying to pass ffmpeg command line options to shrinkwrap though, which won't work. What's happening is shrinkwrap is interpreting the options you've specified for itself (which it doesn't understand), instead of passing them along to ffmpeg underneath.

You need to use the `--ffmpeg-opts` in shrinkwrap to pass raw ffmpeg options, in a comma separated list.

So for example, something like:

```
docker run -v path/to/files:/files bennetimo/shrinkwrap:latest --input-extension mp4 --preset standard --ffmpeg-opts crf=25,preset=veryfast,c:v=libx265 "/files/GOPR0212.mp4"
```

That should get you started with an h265 shrink. Then you can customise the raw ffmpeg params as you need.

Hope that helps
